# Generated by Django 2.2.6 on 2019-10-31 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('building_no', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('Building_name', models.CharField(max_length=10)),
            ],
        ),
    ]
