# Generated by Django 2.2.6 on 2019-11-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191031_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='max_floor',
            field=models.IntegerField(default=0),
        ),
    ]
