# Generated by Django 2.2.6 on 2019-11-05 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_building_min_foor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='min_foor',
            new_name='min_floor',
        ),
    ]
