# Generated by Django 2.2.6 on 2019-11-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20191107_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='change_request_reservation',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='building',
            name='new_request_reservation',
            field=models.IntegerField(default=0),
        ),
    ]
