# Generated by Django 2.2.6 on 2019-11-07 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20191107_1457'),
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='building_no',
            field=models.ForeignKey(db_column='building_no', default=0, on_delete=django.db.models.deletion.CASCADE, related_name='building', to='main.ClassRoom'),
            preserve_default=False,
        ),
    ]
