# Generated by Django 2.2.6 on 2019-11-07 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_reservation_building_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='room_no',
            field=models.ForeignKey(db_column='room_no', on_delete=django.db.models.deletion.CASCADE, related_name='room', to='main.ClassRoom'),
        ),
    ]
