# Generated by Django 2.2.6 on 2019-11-15 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_auto_20191107_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='personnel',
            field=models.IntegerField(default=0),
        ),
    ]
